# .github/workflows/pipeline.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ---------- Backend ----------
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: |
          pip install -r backend/requirements.txt
          ruff check backend
          pytest backend -q

      # ---------- Frontend ----------
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: |
          cd frontend
          npm ci
          npm run lint
          npm run test:unit -- --run

      # ---------- (Optional) Docker build ----------
      - name: Build images
        run: docker compose -f docker-compose.yml build --no-cache
