FROM debian:stable-slim

RUN apt-get update && apt-get -y install cron python3 python3-pip

WORKDIR /app

COPY backend/requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

RUN crontab crontab

CMD ["cron", "-f", "-L", "/dev/stdout"]