// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPWLGnRmbegpu2F5KJWvmTDOfonJoXI4M',
    appId: '1:389441895583:web:c5808ae67ed3e52e0ff6aa',
    messagingSenderId: '389441895583',
    projectId: 'campusmate-40439',
    authDomain: 'campusmate-40439.firebaseapp.com',
    storageBucket: 'campusmate-40439.firebasestorage.app',
    measurementId: 'G-DH8BVBKKXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZzTxzb6tACMwR7AptzCtW1_Z0nAokcXU',
    appId: '1:389441895583:android:5f4635c1eb1fc5780ff6aa',
    messagingSenderId: '389441895583',
    projectId: 'campusmate-40439',
    storageBucket: 'campusmate-40439.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA1ba5RoRxTcQcGPlmJnvxMSdqEkNSsBs',
    appId: '1:389441895583:ios:728ed34f4ceb535c0ff6aa',
    messagingSenderId: '389441895583',
    projectId: 'campusmate-40439',
    storageBucket: 'campusmate-40439.firebasestorage.app',
    iosClientId: '389441895583-e2h912a33fg6cl7icsnhq4882qup1ouv.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA1ba5RoRxTcQcGPlmJnvxMSdqEkNSsBs',
    appId: '1:389441895583:ios:728ed34f4ceb535c0ff6aa',
    messagingSenderId: '389441895583',
    projectId: 'campusmate-40439',
    storageBucket: 'campusmate-40439.firebasestorage.app',
    iosClientId: '389441895583-e2h912a33fg6cl7icsnhq4882qup1ouv.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPWLGnRmbegpu2F5KJWvmTDOfonJoXI4M',
    appId: '1:389441895583:web:26a70c1f7670dfde0ff6aa',
    messagingSenderId: '389441895583',
    projectId: 'campusmate-40439',
    authDomain: 'campusmate-40439.firebaseapp.com',
    storageBucket: 'campusmate-40439.firebasestorage.app',
    measurementId: 'G-H7R0GKMJLW',
  );
}
