"""Add schedule to User and StudyGroup

Revision ID: b93ecfdba326
Revises: c418576bf1f3
Create Date: 2025-08-05 00:49:06.564965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93ecfdba326'
down_revision: Union[str, Sequence[str], None] = 'c418576bf1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_groups', sa.Column('schedule', sa.String(), nullable=True))
    op.add_column('users', sa.Column('schedule', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'schedule')
    op.drop_column('study_groups', 'schedule')
    # ### end Alembic commands ###
