"""Initial migration

Revision ID: c418576bf1f3
Revises: 
Create Date: 2025-08-05 00:47:43.818280

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'c418576bf1f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
